# Generated by Django 4.2.2 on 2023-06-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='followed_users',
            new_name='following',
        ),
    ]
